/* AUTO-GENERATED BY SHOP ADMIN V3 */
const SHOP = {
  "name": "BALAJI GARMENTS",
  "ownerWhatsApp": "919532328020",
  "bannerImage": "banner.jpg",
  "headerLogo": "logo.jpg",
  "websiteUrl": "https://balaji-pbh.github.io/"
};

// ================= CATEGORIES =================
const CATEGORIES = [

];

// ================= PRODUCTS =================
const PRODUCTS = [

];
