/* AUTO-GENERATED BY SHOP ADMIN V3 */
const SHOP = {
  "name": "BALAJI GARMENTS",
  "ownerWhatsApp": "919532328020",
  "bannerImage": "banner.jpg",
  "headerLogo": "logo.jpg",
  "websiteUrl": "https://balaji-pbh.github.io/"
};

// ================= CATEGORIES =================
const CATEGORIES = [
  {
    "id": "wk1",
    "name": "Women Kurti",
    "image": "https://ibb.co/ynxt3qdJ",
    "seo": {
      "title": "Women Kurti | Balaji Garments",
      "description": "Discover the latest Women's Kurtis at Balaji Garments & Saree Centre with stylish designs, premium fabrics, and comfortable fits. Perfect for daily wear, office, college, festivals, and casual occasions. Enjoy trendy fashion at affordable prices with excellent quality. Shop now for the latest collection at the best prices.",
      "keywords": "Women Kurti, Short kurti, Stylish kurti",
      "slug": "women-kurti"
    }
  }
];

// ================= PRODUCTS =================
const PRODUCTS = [];
